go-vela/sdk-go

go.mod
go.sum
vela/admin.go
vela/admin_test.go
vela/client.go
vela/client_test.go

This PR adds all the [admin](https://github.com/go-vela/server/tree/master/api/admin) endpoints to the SDK to make them available to admins who need to script against the endpoints.
The following is example syntax to access the admin endpoints on a client:
```go
client.Admin.Build.GetAll(nil)
```
_Note: GoDoc examples was not added at this time but can be if we think it's valuable._
Dependent PRs:
https://github.com/go-vela/mock/pull/75
fixes: go-vela/community#100

feat: add admin endpoints

---

.github/CONTRIBUTING.md
.golangci.yml
vela/admin.go
vela/authentication.go
vela/build.go
vela/client.go
vela/client_test.go
vela/deployment.go
vela/hook.go
vela/log.go
vela/pipeline.go
vela/repo.go
vela/secret.go
vela/service.go
vela/step.go
vela/worker.go

Continuation of the efforts from https://github.com/go-vela/mock/pull/76 and https://github.com/go-vela/types/pull/122
* Updating the contributing guide to include fixing linter warnings if any are present
* Skipping the `dupl` and `lll` linters on `*_test.go` files
* Added `nolint` directives across the repo to address any current linter issues

chore: linter setup and fixes, doc changes

---

go.mod
go.sum

This updates the following dependencies to `v0.8.0-rc2`:
* `github.com/go-vela/mock`
* `github.com/go-vela/types`

chore: upgrade go-vela deps on v0.8.0-rc2

---

version/version.go

forgot to bump version in the `version` package 😲

chore(version): bump version

---

.github/workflows/release.yml
.github/workflows/reviewdog.yml
.github/workflows/test.yml
.github/workflows/validate.yml
go.mod

Updates Go to 1.17, GitHub Actions pipelines included.
xref: go-vela/types#221

chore(deps): update go to 1.17

---

vela/build.go

xref: https://github.com/go-vela/server/pull/586

enhance(build): add before and after params to sdk

---

vela/build.go

In https://github.com/go-vela/sdk-go/pull/166, I mistakenly declared the `before` and `after` query params as type `int`, rather than type `int64`, which is the correct type.

fix(build): changing int to int64

---

vela/client.go
vela/doc.go
vela/service.go
vela/step.go

Addresses:
- leading spaces with `nolint` directive
- run `gofmt` on all files for formatting
- replace `io/ioutil` with `io` or `os`

chore(lint): address all linter errors in sdk-go

---

vela/admin.go
vela/admin_test.go

Related to: https://github.com/go-vela/server/pull/734
Remove these functions, as they will now return `404`.

enhance(admin): remove get-all functions

---

go.mod
go.sum
vela/authentication.go
vela/authentication_test.go
vela/build.go
vela/build_test.go

PR for sdk-go changes for epic 1: Build Tokens.
Changes:
- Add `GetBuildToken` to the SDK. This will be called by the worker whenever a build is popped off the queue.

feat(build_token): sdk changes for build token implementation

---

go.mod
go.sum
vela/admin.go
vela/admin_test.go
vela/authentication.go
vela/authentication_test.go
vela/client.go
vela/client_test.go
vela/worker.go
vela/worker_test.go

this adds the server functionality introduced in https://github.com/go-vela/server/pull/790
it also cleans up a couple tests

feat: worker auth endpoints

---

vela/service.go
vela/service_test.go
vela/step.go
vela/step_test.go

This is the SDK side of this change: https://github.com/go-vela/server/pull/799

chore: Delete unused `/stream` endpoints

---

vela/admin.go

solves a use-case where a valid but bogus address is given to the `add worker` command
```
add worker --worker.address https://google.com/ --worker.hostname worker
```

fix(register): return error on non-200 response

---

go.mod
go.sum
vela/log.go
vela/log_test.go

Ref: https://github.com/go-vela/server/pull/879
Updating the SDK to account for changes made in the above server PR.

enhance(log): do not return log library type on add / update

---

go.mod
go.sum
vela/scm.go

Ref: https://github.com/go-vela/server/pull/994

fix(repo/sync)!: use PATCH over GET

---

vela/worker.go
vela/worker_test.go

Follow up from https://github.com/go-vela/server/pull/1029

enhance(workers): add list filters for GetAll

---

go.mod
go.sum
vela/pipeline.go
vela/pipeline_test.go

See [server PR that removed this](https://github.com/go-vela/server/pull/1052)

fix(pipeline): remove template opt

---

.github/workflows/codeql-analysis.yml
.github/workflows/reviewdog.yml
.github/workflows/test.yml
.github/workflows/validate.yml

Purposely left the codeql on the older version to test renovate in https://github.com/go-vela/sdk-go/pull/284

chore(ci): include minor and patch versions in workflows

---

go.mod
go.sum
vela/admin_test.go
vela/repo_test.go
vela/secret_test.go

see: https://github.com/go-vela/types/pull/362

chore: delete legacy allow event fields

---

go.mod
go.sum
vela/pipeline.go
vela/pipeline_test.go

Follow up from https://github.com/go-vela/server/pull/1076
Will allow users to purge their pipelines of unwanted steps given a ruledata set

enhance(pipeline): add ruledata options to various pipeline calls

---

go.mod
go.sum
vela/admin.go
vela/admin_test.go
vela/repo.go
vela/repo_test.go
vela/secret_test.go

Follow up from https://github.com/go-vela/server/pull/1095

refactor(repo): use nested repository type

---

go.mod
go.sum
vela/admin.go
vela/admin_test.go
vela/build.go
vela/build_test.go

Ref: https://github.com/go-vela/server/pull/1111

refactor(build): nested API + migration to server types

---

go.mod
go.sum
vela/schedule.go
vela/schedule_test.go

Moved `Schedule` out of `go-vela/types` and into `go-vela/server`. Updated imports in CLI to reflect those changes.
https://github.com/go-vela/server/pull/1108

refactor(schedule): nested API + migration to server types

---

.github/workflows/version_increment.yml

sometimes we forget to bump the version. this should help.
in short, this new Actions workflow will create a PR to bump the version whenever we cut a release that bumps the minor version, ignoring release candidates.

chore(ci): workflow to bump version

---

go.mod
go.sum
vela/admin.go
vela/admin_test.go
vela/authentication.go
vela/authentication_test.go
vela/build.go
vela/build_test.go
vela/client.go
vela/dashboard.go
vela/deployment.go
vela/hook.go
vela/log.go
vela/log_test.go
vela/pipeline.go
vela/queue.go
vela/queue_test.go
vela/repo.go
vela/schedule.go
vela/secret.go
vela/service.go
vela/step.go
vela/worker.go
vela/worker_test.go

Follow up from https://github.com/go-vela/server/pull/1213

refactor: remove types dependency

---

.golangci.yml
vela/client.go

used `golangci-lint migrate` to update config file

chore(linter): update config to v2
